[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerfileNoCache = true

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckPath = "/"
healthcheckTimeout = 120
numReplicas = 1
